package com.healthcareai.service;

import java.security.SecureRandom;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.healthcareai.dto.TenantAdminPasswordResetResponse;
import com.healthcareai.dto.UserPasswordResetResponse;
import com.healthcareai.entity.Role;
import com.healthcareai.entity.User;
import com.healthcareai.exception.BusinessRuleViolationException;
import com.healthcareai.exception.ResourceNotFoundException;
import com.healthcareai.repository.UserRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@RequiredArgsConstructor
@Slf4j
public class UserServiceImpl implements UserService {

    // Excludes visually-ambiguous characters (0/O, 1/I/l) so the temporary
    // password generated by resetTenantAdminPassword/resetStaffPassword is
    // easy to read back and retype over a phone call.
    private static final String TEMP_PASSWORD_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
    private static final int TEMP_PASSWORD_LENGTH = 12;

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final RefreshTokenService refreshTokenService;
    private final SecureRandom secureRandom = new SecureRandom();

    @Override
    @Transactional
    public User createUser(String email, String rawPassword, String fullName, Role role, UUID tenantId) {
        if (userRepository.existsByEmailIgnoreCase(email)) {
            throw new BusinessRuleViolationException("A user with this email already exists.");
        }
        User user = User.builder()
                .tenantId(tenantId)
                .email(email)
                .passwordHash(passwordEncoder.encode(rawPassword))
                .fullName(fullName)
                .role(role)
                .enabled(true)
                .build();
        return userRepository.save(user);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<User> findByEmail(String email) {
        return userRepository.findByEmailIgnoreCase(email);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<User> findById(UUID userId) {
        return userRepository.findById(userId);
    }

    @Override
    @Transactional
    public void setPassword(UUID userId, String newRawPassword) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> ResourceNotFoundException.of("User", userId));
        user.setPasswordHash(passwordEncoder.encode(newRawPassword));
        userRepository.save(user);
        refreshTokenService.revokeAllForUser(userId);
    }

    @Override
    @Transactional
    public void changePassword(String email, String currentPassword, String newPassword) {
        User user = userRepository.findByEmailIgnoreCase(email)
                .orElseThrow(() -> new BadCredentialsException("Invalid current password."));
        if (!passwordEncoder.matches(currentPassword, user.getPasswordHash())) {
            throw new BadCredentialsException("Invalid current password.");
        }
        user.setPasswordHash(passwordEncoder.encode(newPassword));
        userRepository.save(user);
        refreshTokenService.revokeAllForUser(user.getId());
    }

    @Override
    @Transactional(readOnly = true)
    public List<User> findByTenant(UUID tenantId) {
        return userRepository.findByTenantId(tenantId);
    }

    @Override
    @Transactional(readOnly = true)
    public long count() {
        return userRepository.count();
    }

    @Override
    @Transactional(readOnly = true)
    public long countByTenant(UUID tenantId) {
        return userRepository.countByTenantId(tenantId);
    }

    @Override
    @Transactional
    public TenantAdminPasswordResetResponse resetTenantAdminPassword(UUID tenantId) {
        User admin = userRepository.findFirstByTenantIdAndRoleOrderByCreatedAtAsc(tenantId, Role.ADMIN)
                .orElseThrow(() -> new BusinessRuleViolationException("This clinic has no admin account to reset."));

        String temporaryPassword = generateTemporaryPassword();
        admin.setPasswordHash(passwordEncoder.encode(temporaryPassword));
        userRepository.save(admin);
        refreshTokenService.revokeAllForUser(admin.getId());
        log.info("Super admin reset the password for tenant {} admin {}", tenantId, admin.getEmail());

        return new TenantAdminPasswordResetResponse(admin.getEmail(), temporaryPassword);
    }

    @Override
    @Transactional
    public User setStaffEnabled(UUID tenantId, UUID userId, boolean enabled, String callerEmail) {
        User user = userRepository.findById(userId)
                .filter(u -> u.getTenantId().equals(tenantId))
                .orElseThrow(() -> ResourceNotFoundException.of("User", userId));

        if (!enabled) {
            if (user.getEmail().equalsIgnoreCase(callerEmail)) {
                throw new BusinessRuleViolationException("You cannot deactivate your own account.");
            }
            if (user.getRole() == Role.ADMIN) {
                boolean anyOtherActiveAdmin = userRepository.findByTenantId(tenantId).stream()
                        .anyMatch(u -> u.getRole() == Role.ADMIN && u.isEnabled() && !u.getId().equals(userId));
                if (!anyOtherActiveAdmin) {
                    throw new BusinessRuleViolationException(
                            "This clinic must have at least one active administrator.");
                }
            }
        }

        user.setEnabled(enabled);
        User saved = userRepository.save(user);
        if (!enabled) {
            // Deactivating mid-session shouldn't leave their existing login
            // usable until the access token happens to expire on its own.
            refreshTokenService.revokeAllForUser(userId);
        }
        log.info("Staff account {} {} within tenant {} by {}", saved.getEmail(),
                enabled ? "enabled" : "disabled", tenantId, callerEmail);
        return saved;
    }

    @Override
    @Transactional
    public UserPasswordResetResponse resetStaffPassword(UUID tenantId, UUID userId) {
        User user = userRepository.findById(userId)
                .filter(u -> u.getTenantId().equals(tenantId))
                .orElseThrow(() -> ResourceNotFoundException.of("User", userId));

        String temporaryPassword = generateTemporaryPassword();
        user.setPasswordHash(passwordEncoder.encode(temporaryPassword));
        userRepository.save(user);
        refreshTokenService.revokeAllForUser(user.getId());
        log.info("Admin reset the password for staff member {} in tenant {}", user.getEmail(), tenantId);

        return new UserPasswordResetResponse(user.getEmail(), temporaryPassword);
    }

    private String generateTemporaryPassword() {
        StringBuilder password = new StringBuilder(TEMP_PASSWORD_LENGTH);
        for (int i = 0; i < TEMP_PASSWORD_LENGTH; i++) {
            password.append(TEMP_PASSWORD_ALPHABET.charAt(secureRandom.nextInt(TEMP_PASSWORD_ALPHABET.length())));
        }
        return password.toString();
    }
}
